project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: graphs.qmd
        text: Data Analysis
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About
   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

